export const booksData = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publication_year: 1960,
    category: "Fiction",
    description:
      "A classic novel depicting racial injustice in the American South.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    publication_year: 1949,
    category: "Fiction",
    description: "A dystopian novel portraying a totalitarian society.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publication_year: 1813,
    category: "Classic",
    description:
      "A classic novel exploring themes of love, marriage, and social norms.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publication_year: 1925,
    category: "Classic",
    description:
      "A tale of the American Dream, wealth, and love during the Roaring Twenties.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 5,
    title: "Moby-Dick",
    author: "Herman Melville",
    publication_year: 1851,
    category: "Fiction",
    description:
      "The epic tale of Captain Ahab's obsession with the white whale.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 6,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    publication_year: 1954,
    category: "Fantasy",
    description:
      "An epic fantasy saga about the quest to destroy the One Ring.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publication_year: 1951,
    category: "Fiction",
    description:
      "A classic coming-of-age novel following Holden Caulfield's journey.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 8,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publication_year: 1937,
    category: "Fantasy",
    description:
      "The prequel to The Lord of the Rings, following Bilbo Baggins' journey.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 9,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    publication_year: 1967,
    category: "Fiction",
    description:
      "A multi-generational saga of the Buendía family in the fictional town of Macondo.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 10,
    title: "War and Peace",
    author: "Leo Tolstoy",
    publication_year: 1869,
    category: "Fiction",
    description:
      "A monumental work depicting the events of Russian society during the Napoleonic era.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 11,
    title: "The Odyssey",
    author: "Homer",
    publication_year: "8th century BCE",
    category: "Mythology",
    description:
      "An ancient Greek epic poem recounting Odysseus' ten-year journey home after the Trojan War.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 12,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    publication_year: "1320",
    category: "Poetry",
    description:
      "An epic poem that follows the journey of the soul through Hell, Purgatory, and Heaven.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 13,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    publication_year: 1880,
    category: "Classic",
    description:
      "A complex novel exploring themes of spirituality, morality, and human nature.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 14,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    publication_year: 1866,
    category: "Classic",
    description:
      "A psychological thriller revolving around guilt, conscience, and redemption.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 15,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    publication_year: 1890,
    category: "Fiction",
    description:
      "A novel about a man whose portrait ages while he retains his youth and beauty.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 16,
    title: "Brave New World",
    author: "Aldous Huxley",
    publication_year: 1932,
    category: "Fiction",
    description:
      "A dystopian vision of a future society obsessed with pleasure and conformity.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 17,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    publication_year: 1844,
    category: "Fiction",
    description:
      "An adventure novel of revenge, love, and redemption set in the early 19th century.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 18,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    publication_year: 1877,
    category: "Classic",
    description:
      "A tragic love story set against the backdrop of Russian high society.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 19,
    title: "The Alchemist",
    author: "Paulo Coelho",
    publication_year: 1988,
    category: "Fiction",
    description:
      "A philosophical novel about a shepherd boy's journey to find his personal legend.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 20,
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    publication_year: 1884,
    category: "Adventure",
    description:
      "A satirical novel following Huck Finn's journey down the Mississippi River.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 21,
    title: "The Iliad",
    author: "Homer",
    publication_year: "8th century BCE",
    category: "Mythology",
    description:
      "An ancient Greek epic poem about the Trojan War and the hero Achilles.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 22,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    publication_year: 1954,
    category: "Fantasy",
    description:
      "A thrilling epic about the quest to destroy the One Ring and save Middle-earth from the dark lord Sauron.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 23,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    publication_year: 1605,
    category: "Classic",
    description:
      "A satirical novel about a deluded knight and his faithful squire, Sancho Panza.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 24,
    title: "Frankenstein",
    author: "Mary Shelley",
    publication_year: 1818,
    category: "Fiction",
    description:
      "A novel about the creation of a monster and the consequences of playing god.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 25,
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    publication_year: 1865,
    category: "Fantasy",
    description:
      "A whimsical tale about a girl named Alice who falls into a magical world.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 26,
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    publication_year: 1943,
    category: "Classic",
    description:
      "A philosophical novella about a young prince's journey through the universe.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 27,
    title: "The Book Thief",
    author: "Markus Zusak",
    publication_year: 2005,
    category: "Fiction",
    description: "A story of a girl living in Nazi Germany, narrated by Death.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 28,
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    publication_year: 1969,
    category: "Fiction",
    description: "An anti-war novel that mixes science fiction and dark humor.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 29,
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    publication_year: 1939,
    category: "Fiction",
    description:
      "A novel about the plight of migrant workers during the Great Depression.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 30,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    publication_year: 1953,
    category: "Fiction",
    description:
      "A dystopian novel depicting a future society where books are banned.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 31,
    title: "The Lord of the Flies",
    author: "William Golding",
    publication_year: 1954,
    category: "Fiction",
    description:
      "A novel about a group of British boys stranded on an uninhabited island.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 32,
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    publication_year: 1979,
    category: "Fiction",
    description:
      "A comedic science fiction series about the misadventures of Arthur Dent.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 33,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    publication_year: 1859,
    category: "Classic",
    description:
      "A historical novel set during the French Revolution, exploring themes of sacrifice and resurrection.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 34,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    publication_year: 1950,
    category: "Fantasy",
    description:
      "A series of fantasy novels set in the magical land of Narnia.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 35,
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    publication_year: 1985,
    category: "Fiction",
    description:
      "A dystopian novel set in a totalitarian society where women are subjugated.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 36,
    title: "The Name of the Rose",
    author: "Umberto Eco",
    publication_year: 1980,
    category: "Fiction",
    description: "A medieval mystery novel set in an Italian monastery.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 37,
    title: "The Trial",
    author: "Franz Kafka",
    publication_year: 1925,
    category: "Fiction",
    description: "A surreal novel exploring themes of guilt, law, and justice.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 38,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    publication_year: 2003,
    category: "Fiction",
    description:
      "A novel about friendship, redemption, and the impact of war in Afghanistan.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 39,
    title: "The Pillars of the Earth",
    author: "Ken Follett",
    publication_year: 1989,
    category: "Fiction",
    description:
      "An epic historical novel set in 12th-century England, centered around the construction of a cathedral.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 40,
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    publication_year: 2001,
    category: "Mystery",
    description:
      "A mystery novel set in post-war Barcelona, revolving around a forgotten book and its author.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 41,
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    publication_year: 1911,
    category: "Classic",
    description:
      "A classic children's novel about a young girl who discovers a hidden garden.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 42,
    title: "The Giver",
    author: "Lois Lowry",
    publication_year: 1993,
    category: "Fantasy",
    description:
      "A dystopian novel about a society with strict control over emotions and memories.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 43,
    title: "The Metamorphosis",
    author: "Franz Kafka",
    publication_year: 1915,
    category: "Fiction",
    description:
      "A novella about a man who wakes up one morning transformed into a giant insect.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 44,
    title: "Gone with the Wind",
    author: "Margaret Mitchell",
    publication_year: 1936,
    category: "Romance",
    description:
      "A historical novel set during the American Civil War, centered around Scarlett O'Hara.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 45,
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    publication_year: 1908,
    category: "Fantasy",
    description:
      "A children's novel about the adventures of anthropomorphic animals.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 46,
    title: "Dracula",
    author: "Bram Stoker",
    publication_year: 1897,
    category: "Classic",
    description:
      "A Gothic horror novel about the vampire Count Dracula's attempt to move to England.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 47,
    title: "The Call of the Wild",
    author: "Jack London",
    publication_year: 1903,
    category: "Adventure",
    description:
      "An adventure novel about a domestic dog's life in the wilds of the Yukon.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 48,
    title: "The Stand",
    author: "Stephen King",
    publication_year: 1978,
    category: "Mystery",
    description:
      "A post-apocalyptic horror novel about a deadly pandemic and its aftermath.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 49,
    title: "The Color Purple",
    author: "Alice Walker",
    publication_year: 1982,
    category: "Fiction",
    description:
      "A novel about the life of African-American women in the Southern United States.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
  {
    id: 50,
    title: "The Silmarillion",
    author: "J.R.R. Tolkien",
    publication_year: 1977,
    category: "Fantasy",
    description:
      "A collection of mythopoeic stories about the history of Middle-earth.",
    cover_image: "https://fakeimg.pl/667x1000/cc6600",
  },
];
